name: Execução de testes regressivos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout projeto
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: npm install

      - name: Run ci:build
        uses: npm run ci:build

      - name: Run tests
        uses: npm run test:ci
